name: lao_location_prediction
description: "A flutter package that predicts Laos locations"
version: 0.0.2
repository: https://github.com/SouksavathPMS/lao-location-prediction
issue_tracker: https://github.com/SouksavathPMS/lao-location-prediction/issues


environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
    assets:
    - assets/lao_places.json
    - assets/grid_metadata.json
    - assets/default_data.json
    - assets/cells/
    - assets/images/qr.jpg
    - assets/images/example.gif

example: example/main.dart


  

  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
